### PR TITLE
fix(Dropdown): list icon was clickable in disabled state

### PR DESCRIPTION
**Pull request by patoi**
https://user-images.githubusercontent.com/1846548/149938326-e2ab9415-3178-429d-bbf7-0f0cdd66a529.mp4

### CODE REVIEW

**Comment by patoi** [comment]
There is one more bug...

**Comment by patoi** [comment]
ListBox was selectable, when extended Dropdown component.

**Comment by patoi** [comment]
MacOS 12.1:
The bug does **not** reproducable in Firefox 96.0.1.
Affected browser is Chrome 97.0.4692.71 (x86_64)

**Review by metonym — APPROVED** [review]
Nice catch 🙏

**Comment by metonym** [comment]
Fixed in [v0.53.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.53.0)

**Pull request merged**
