### PR TITLE
fix(ToolTip): better toggling logic

### PR DESCRIPTION
**Pull request by malinowskip**
Proposal to fix https://github.com/carbon-design-system/carbon-components-svelte/issues/872

### CODE REVIEW

**Comment by metonym** [comment]
Thank you for taking the time. I'm still encountering the following behavior.

Clicking the button once will double trigger the tooltip – it will open and close it in fast succession.

https://user-images.githubusercontent.com/10718366/139747955-eceb0c38-6430-4205-a0bf-eeb572f94dfb.mov

**Comment by malinowskip** [comment]
Thanks for reviewing. How can I open that example? I don’t know what the route should be.

**Comment by metonym** [comment]
> Thanks for reviewing. How can I open that example? I don’t know what the route should be.

The route should be `http://localhost:3000/framed/Tooltip/TooltipReactive`

I tested it with the previous code (before the [commit](https://github.com/malinowskip/carbon-components-svelte/commit/f155486c373d6b0ddedd89284a8e02b34ff98458) that modified the example):

```svelte
<!-- TooltipReactive.svelte -->
<script>
  import { Tooltip, Button } from "carbon-components-svelte";
  let open = true;
</script>

<style>
  div {
    margin-top: var(--cds-spacing-05);
  }
</style>

<Tooltip bind:open triggerText="Resource list" align="start">
  <p>Resources are provisioned based on your account's organization.</p>
</Tooltip>

<div style="margin-top: var(--cds-spacing-12);">
  <Button size="small" on:click="{() => (open = !open)}">
    {open ? 'Close tooltip' : 'Open tooltip'}
  </Button>
</div>

<div>Open: {open}</div>

```

**Comment by malinowskip** [comment]
Okay, I think I get it now. The "Open tooltip" button opens the tooltip, but it still triggers this mousedown handler in the ToolTip component:

```svelte
<svelte:window
  on:mousedown="{({ target }) => {
    if (open) {
      if (target.contains(refTooltip)) {
        if (refIcon) {
          refIcon.focus();
        } else if (ref) {
          ref.focus();
        }
      }

      if (!ref.contains(target)) open = false;
    }
  }}"
/>
```

**Comment by metonym** [comment]
Unfortunately, it reintroduces this issue where multiple tooltips can be open at the same time: https://github.com/carbon-design-system/carbon-components-svelte/issues/869

**Comment by malinowskip** [comment]
Thank you for reviewing. I tried a bunch of different things, but it seems like each fix introduces a regression one way or another – in most cases due to event handlers firing at different times, doing conflicting things. For example, in the reactive example, the `mousedown` event on the button closes the tooltip, so the “Close tooltip” button becomes an “Open tooltip” button mid-click.

The only thing I can think of at this point is to use a store to ensure that only one ToolTip is open at any given time, but that might be overkill if there’s a simpler solution.

**Comment by malinowskip** [comment]
I have tested this with all the examples in the docs, the reactive example, as well as the “multiple tooltips” example, in Firefox and Chrome. To deal with the race conditions, I registered the new click event in the capture phase, and used a timeout. @metonym when you have a chance, can you have a look? I hope I didn’t miss anything obvious this time.

There is an unrelated minor issue where if you open a tooltip, click on it, and then tab out, then it remains open.

**Review by metonym — APPROVED** [review]
Well done!

**Pull request merged**
