### PR TITLE
fix(overflow-menu): use `offsetWidth`, `offsetHeight` to compute menu dimensions

### PR DESCRIPTION
**Pull request by Sahasrara**

### CODE REVIEW

**Comment by metonym** [comment]
Could you provide an example or some context as to what this solves?

**Comment by Sahasrara** [comment]
> Could you provide an example or some context as to what this solves?

Oh sorry, so specifically I was using these dropdowns nested inside an element with scale transformation applied to it. The client rect calculations actually takes the scale into account so if you use those values to position the dropdown menu, the menu will appear in the wrong position in that context.

Here's a much more specific example:
https://svelteflow.dev/examples

Imagine a dropdown on one of the nodes in the graph on this page. The position of the dropdown will be incorrect if you zoom in or out since they use transform scale.

**Review by metonym — APPROVED** [review]
Seems like a reasonable approach.

**Comment by metonym** [comment]
Released in [v0.82.11](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.82.11).

**Pull request merged**
