### PR TITLE
Update Carbon to version 11

### LINKED ISSUE #1253: When will Carbon v11 be available for Svelte?
(title).
Thanks.

### PR DESCRIPTION
**Pull request by gregorw**
This PR introduces v11 carbon styles. As a first step, I would make sure that all existing components still work, before introducing new components or altering existing ones.

Here’s the list of components that need to be verified (patches welcome):

- [x] @carbon/styles
- [x] @ibm/plex
- [ ] Accordion
- [ ] AspectRatio
- [ ] Breadcrumb
- [ ] Breakpoint
- [ ] Button
- [ ] ButtonSet
- [ ] Checkbox
- [ ] ClickableTile
- [ ] CodeSnippet
- [ ] ComboBox
- [ ] ComposedModal
- [ ] ContentSwitcher
- [ ] ContextMenu
- [ ] CopyButton
- [ ] DataTable
- [ ] DatePicker
- [ ] Dropdown
- [ ] ExpandableTile
- [ ] FileUploader
- [ ] FluidForm
- [ ] Form
- [ ] Grid
- [ ] ImageLoader
- [ ] InlineLoading
- [ ] InlineNotification
- [ ] Link
- [ ] Loading
- [ ] LocalStorage
- [ ] Modal
- [ ] MultiSelect
- [ ] NumberInput
- [ ] OrderedList
- [ ] OverflowMenu
- [ ] Pagination
- [ ] PaginationNav
- [ ] PasswordInput
- [ ] Popover
- [ ] ProgressBar
- [ ] ProgressIndicator
- [ ] RadioButton
- [ ] RadioTile
- [ ] RecursiveList
- [ ] Search
- [ ] Select
- [ ] SelectableTile
- [ ] SkeletonPlaceholder
- [ ] SkeletonText
- [ ] Slider
- [ ] StructuredList
- [ ] Tabs
- [ ] Tag
- [ ] TextArea
- [ ] TextInput
- [ ] Theme
- [ ] Tile
- [ ] TimePicker
- [ ] ToastNotification
- [ ] Toggle
- [ ] Tooltip
- [ ] TooltipDefinition
- [ ] TooltipIcon
- [ ] TreeView
- [ ] Truncate
- [ ] UIShell
- [ ] UnorderedList

The current state is deployed here: https://carbon-components-svelte-v11.onrender.com

The roadmap to 1.0 https://github.com/carbon-design-system/carbon-components-svelte/discussions/1614 will defines later steps.

Fixes #1253.

—

Other resources and onsiderations

- [ ] Components
  - [ ] [Notifications](https://carbondesignsystem.com/migrating/guide/design#notifications-breaking)
    - [ ] [`ActionableNotification`](https://carbondesignsystem.com/components/notification/usage/#actionable-notifications)
    - [ ] Remove action from `InlineNotification`
  - [ ] [`Popover`](https://carbondesignsystem.com/migrating/guide/design#popover-new)
  - [ ] [`Tooltip`](https://carbondesignsystem.com/migrating/guide/design#tooltip-breaking): Refactor to use Popover
  - [ ] [`Toggletip`](https://carbondesignsystem.com/migrating/guide/design#toggletip-new)
  - [ ] Refactor [Tabs](https://carbondesignsystem.com/migrating/guide/design#tabs-breaking)
  - [ ] [`UIShell`](https://carbondesignsystem.com/migrating/guide/design#ui-shell-updated)
- [ ] Sizing
- [ ] Type tokens
- [ ] Color tokens
- [ ] Theming
  - [ ] `Theme` component (see also fac78ee4aad272e60b6ebfbdc64fdc2d7ef95471)
  - [ ] `Layer` component
  - [ ] Remove `light` variants

### CODE REVIEW

**Comment by theetrain** [comment]
Hi @gregorw, thank you very much for taking the time to explore v11 style adoption! I have recently posted our v1 roadmap announcement here; https://github.com/carbon-design-system/carbon-components-svelte/discussions/1614 please have a look.

For v11 styles and tokens, we're considering to use SCSS directly in carbon-components-svelte, which would require consumers to have [vitePreprocess](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md) installed so that when they import components such as `import { Button } from 'carbon-components-svelte`, it will have `@use` directives for its corresponding styles set up. With [svelte-add](https://github.com/svelte-add/svelte-add) we can make it easy for folks to set up carbon-components-svelte with SCSS in one command.

Let us know your thoughts here or in the announcement above.

**Comment by gregorw** [comment]
Hi @theetrain, thanks for your comment and the roadmap write up. This sounds great! 

When it comes to using Carbon styles on a component basis instead of a global import I have tinkered with this here: https://github.com/gregorw/svelte-carbon-v11. In general, I like the idea and a first draft looks promising.

At the same time, I believe it is required to load some **global resets and styles anyways**. Also, I’m not entirely sure how configuration works like this since **a global configuration would need to be handed down into all individual components**, e.g. `$use-flexbox-grid`, `$prefix`, …

Also, when including styles within the components, some warnings may come up like this:

```
Plugin svelte: Unused CSS selector ".cds--btn-set--stacked .cds--btn.cds--btn--disabled:first-of-type"
```

Since this is a Svelte warning it won’t be shown on a global SCSS import.

I wonder what the benefit of a per-component style import really is. It seems to me that handing down global configuration into each component and dealing with a number of svelte warnings could be cumbersome, considering that the global import will probably still be required for resets. But it’s certainly worth trying. I may also be missing something since I have limited experience with Dart Sass.

For some stats: Total bundle sizes of full `@carbon/styles` import are below:

```
 68K bundle.css
4.9K bundle.js
 86K bundle.js.map
```

Build duration is ~10s.

**Comment by gregorw** [comment]
@theetrain I would suggest to rebase `carbon-v11` branch onto `master`. Then, I’d create smaller PRs onto that intermediate branch. Once `carbon-v11` is stable we can merge to `master`. What do you think? I’m a bit worried that this PR would become too large otherwise. Also, this allows other contributors to verify some of the components.
When it comes to using component based styles, I’d suggest to refactor this after (global) v11 styles have been adopted (this PR) since this would be too many moving parts at the same time from my perspective. cc @metonym

**Comment by theetrain** [comment]
All good points. Right now I'm using the `carbon-v11` branch to experiment with svelte-package and scss to see what performs best for the developer and end user experience. I'll soon move this conversation to a new ticket to keep track of the moving parts and proposal. I'll be sure to mention you when that's up. 😃

I could also move this conversation to #1253 since we have interested folks subscribed there already.

**Comment by gregorw** [comment]
@theetrain I’ll let you be in the lead. Let me know when I can help please. From my point of view the first step on the roadmap “Adopt Carbon v11 styles” is already quite involved. As far as I am concerned I would tackle this first before coming up with new proposals for better developer experience. In short, we should adopt [`@carbon/styles`](https://github.com/carbon-design-system/carbon/tree/main/packages/styles) as first priority.

**Pull request closed without merging**
