### PR TITLE
fix(button): forward `on:focus` event

### LINKED ISSUE #1830: Button `focus()` enhancements
Currently, `Button.svelte` does not forward focus events. Adding `on:focus` to the element would solve this.

Also, to programmatically assign focus, access to the HTML element is required, but currently the Button component does not allow access. Perhaps this would work:

```
export let el: HTMLElement;

<button bind:this={el}
```

Which would allow `buttonInstance.el.focus()` in parent components.

I'm happy to generate a PR if these approaches are acceptable.

### PR DESCRIPTION
**Pull request by ryanbmarx**
Fixes #1830

### CODE REVIEW

**Comment by theetrain** [comment]
This sounds good to me. Please also update the documentation by running `yarn build:docs` and check in changed files.

**Comment by ryanbmarx** [comment]
Committed updated docs

**Comment by brunnerh** [comment]
`focus` is often used with `blur`, would add that as well.

**Comment by ryanbmarx** [comment]
> `focus` is often used with `blur`, would add that as well.

Done.

**Review by metonym — APPROVED** [review]

**Comment by metonym** [comment]
Thanks! Released in [v0.82.8](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.82.8)

**Pull request merged**
