### PR TITLE
Correct page number when dispatching update

### PR DESCRIPTION
**Pull request by ibilux**
When in last page of data and the page size get changed to a bigger size the current page number will be out of range of total pages.
This code will set the page number in range of total pages.

### CODE REVIEW

**Comment by metonym** [comment]
Could you provide a repro?

**Comment by ibilux** [comment]
> Could you provide a repro?

[Here](https://svelte.dev/repl/d7d6bbe381be49d39fb042c4c9aabd63?version=3.44.1),
If you select **10** items per page and select page **5**,
And then select **100** items per page,
The current page will stay **5**, and the "Next page" button will still work and increasing the page number.
# I hope I made it clear?

**Comment by metonym** [comment]
Nice catch – thanks for providing a repro.

As for the failing CI, it seems that Svelte has detected a circular dependency between `page` and `totalPages`.

I think that using the `afterUpdate` lifecycle method should work:

```js
afterUpdate(() => {
  if (page > totalPages) {
    page = totalPages;
  }
});
```

**Comment by ibilux** [comment]
> ```js
> afterUpdate(() => {
>   if (page > totalPages) {
>     page = totalPages;
>   }
> });
> ```

Looks very good.

**Comment by metonym** [comment]
Thanks again for reporting this!

**Comment by metonym** [comment]
Fixed in [v0.49.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.49.2)

**Pull request merged**
