### PR TITLE
fix: outline live text in thumbnail svg

### PR DESCRIPTION
**Pull request by mattrosno**
Closes https://github.com/carbon-design-system/carbon-platform/issues/986

Updates library description specified here: https://github.com/carbon-design-system/carbon-platform/issues/1109

Fixes error found here: https://github.com/carbon-design-system/carbon-platform/pull/1127#issuecomment-1211433470

Test results below.

### CODE REVIEW

**Comment by mattrosno** [comment]
Local test with this indexed (testing the remote branch for this PR):

```js
{
  'carbon-styles': {
    host: 'github.com',
    org: 'carbon-design-system',
    repo: 'carbon',
    path: '/packages/styles',
    maintainer: 'carbon',
    group: carbonComponentsGroup
  },
  'carbon-components-svelte': {
    host: 'github.com',
    org: 'mattrosno',
    repo: 'carbon-components-svelte',
    path: '/',
    group: carbonComponentsGroup,
    ref: 'fix/indexed-description-thumbnail'
  }
}
```

image

image

image

image

image

image

image

image

**Comment by mattrosno** [comment]
All remote thumbnails render.

**Comment by mattrosno** [comment]
The `Inline notification` thumbnail path is fixed.
image

**Comment by mattrosno** [comment]
The `Button set` thumbnail is fixed. `Button` still has text that's rendering a serif font here in Safari. We'll fix that in the `carbon` repo in a different PR.
image

**Comment by mattrosno** [comment]
Button set hover is fixed.
image

**Review by metonym — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
