### PR TITLE
Fix docs dev/build on Windows/newer Node version

### LINKED ISSUE #959: Docs build system out of date?
The `svite` package is on an old version that causes errors with newer versions of node:

> error svite@0.7.2: The engine "node" is incompatible with this module. Expected version "^12||^14". Got "16.7.0"

There appears to be a vite plugin that is [supposed to replace this packge](https://github.com/svitejs/svite/tree/main/packages/svite#migration-from-08).

### PR DESCRIPTION
**Pull request by brunnerh**
Switch from svite to vite + vite-plugin-svelte.
Use `cross-env` to set environment variables platform independently in scripts.

Fixes #959

### CODE REVIEW

**Comment by brunnerh** [comment]
If that should be split or `cross-env` should not be used at all this can be adjusted/rejected as required.

**Comment by brunnerh** [comment]
Also, I do not know what the performance of the `svite` system was like; it seems rather slow now.
This might need additional adjustments to `vite.config.js`.

**Review by metonym — APPROVED** [review]
Awesome – thanks for getting to the bottom of this!

I tested this locally and was able to run `yarn dev` and `yarn build`.

I also deployed it on Render and it works as expected: https://ccs-docs-win.onrender.com/

The build time seems to have drastically improved; it's about ~21% faster.

**Comment by brunnerh** [comment]
@metonym If that is "fast", I am not impressed 😅
The hot module reload in dev modes takes a very long time, not the "almost instant" I am used to from other projects.
I suspect that it rebuilds too many files unnecessarily.

**Comment by metonym** [comment]
@brunnerh True – I was referring to the production build. The current `yarn dev` has been consistently slow as of late. I suspect the bottleneck is related to how many passes the various preprocessors do on all the files.

When testing/developing this library locally, I've mainly been using a fresh SvelteKit project that symlinks "carbon-components-svelte."

Eventually, the goal is to move to SvelteKit.

**Pull request merged**
