### PR TITLE
fix(multi-select): fix sorting behavior for `top-after-reopen`

### LINKED ISSUE #2066: MultiSelect: `top-after-reopen` setting for `selectionFeedback` not being respected
The `top-after-reopen` setting for `selectionFeedback` (default) is currently not being respected. With this setting enabled, selected items should jump to the top after the dropdown is re-opened.

## Reproduction
https://github.com/malinowskip/carbon-multiselect-selection-feedback-error

## Possible solution

Perhaps this could be fixed by including another condition on the following line:
https://github.com/carbon-design-system/carbon-components-svelte/blob/e2342aa249398e4d1e196a48f3fdcfc931370a92/src/MultiSelect/MultiSelect.svelte#L250

For example (assuming that items can be sorted as soon as the dropdown is closed):

```js
if (
  selectedIds.length > 0 &&
  (selectionFeedback === "top" || (selectionFeedback === "top-after-reopen" && !open))
) {
  // sorting logic
}
```

### PR DESCRIPTION
**Pull request by malinowskip**
Fixes #2066

I wrote some tests for the MultiSelect component while looking for possible fixes for https://github.com/carbon-design-system/carbon-components-svelte/issues/2066. If this is a useful addition, I’d be happy to include more cases or make revisions.

### CODE REVIEW

**Review by metonym — APPROVED** [review]
Nice – thank you

**Comment by malinowskip** [comment]
Thanks. I made the tests a bit more exhaustive and included a possible fix. It uses the same encapsulated sorting logic, but it’s moved out of the reactive block.

**Comment by metonym** [comment]
LGTM. Thank you for this – test cases are very thorough.

**Comment by metonym** [comment]
Released in [v0.86.2](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.86.2)

**Comment by malinowskip** [comment]
Thanks! I appreciate it.

**Pull request merged**
