### PR TITLE
Carbon v11 integration

### LINKED ISSUE #1616: Typescript improvements
As advised in https://github.com/carbon-design-system/carbon-components-svelte/discussions/1614#discussioncomment-4618257

- [ ] Switch from `svelte.JSX` to `svelte/elements`
- [ ] Decide whether to use `svelte-package` or augment `sveld`

[`svelte-package`](https://kit.svelte.dev/docs/packaging) allows us to write components with `<script lang=ts>` and ship `carbon-components-svelte` with `.svelte` and `.d.ts` pairs. Sveld is likely still needed to generate documentation.

### LINKED ISSUE #1629: Carbon v11 style integration
This is a placeholder ticket to track the integration of Carbon v11 styles into carbon-components-svelte. Adopting Carbon v11 styles is our highest priority, but shipping components with `<style lang="sass">` is currently problematic with Vite as discussed in #1561.

I'm currently evaluating `@sveltejs/package` in the [`carbon-v11`](https://github.com/carbon-design-system/carbon-components-svelte/tree/feat/carbon-v11) branch in order to accomodate these aspirational goals:

- Write components using `<script lang="ts">` to distribute as JS Svelte components and companion `*.svelte.d.ts` files for TypeScript users
- Import Carbon v11 SCSS directly via `<style lang="sass">@use ...</style>` and rely on `@sveltejs/package` to compile styles into scoped CSS
- Ensure there's a way to theme components via CSS variables once SCSS compiles to scoped CSS in each component
- Test build performance on a plain SvelteKit app

If the above goals turn out to be favourable, we'll proceed to implement Carbon v11 styles into every component. Special thanks to @gregorw for early exploration in #1496.

### PR DESCRIPTION
**Pull request by theetrain**
Closes #1629 
Closes #1616 

⚠️ This should NOT be merged until all components have been converted to using v11 styles. Components should be converted one at a time and reviewed as PRs against the `feat/carbon-v11` branch. We can make incremental releases to the `next` tag.

This PR is meant to track and discuss the progress in #1629.

### General

- Adopt `@sveltejs/package` for building the distributable package as ESM, which also precompiles TypeScript and SCSS
- Upgrade routify to v2 for `/docs`

### Button

- feat: apply v11 styles to Button, ButtonSet, and ButtonSkeleton
- feat: forward focus and blur events
- fix: provide button role for custom elements using 'as'
- BREAKING CHANGE: danger-tertiary and danger-ghost props were renamed to danger--tertiary and danger--ghost (two dashes instead of one)
- BREAKING CHANGE: buttons now have a larger minimum width

### CODE REVIEW

**Comment by theetrain** [comment]
@metonym I've been trying to get `sveld` to generate an updated `COMPONENT_API.json`, but I can't seem to figure it out. Can you help checkout this `feat/carbon-v11` branch and have a look?

**Comment by theetrain** [comment]
That helped, thanks! I use Node 18, and took for granted this feature. Perhaps editing carbon-components-svelte can be done with Node 18, but we can allow users to use Node 16?

I could also make these imports backwards-compatible using the tip here: https://stackoverflow.com/a/74504130/2545443

Other observations:
- sveld doesn't recognize types from `svelte/elements`; we'll need to account for that when generating JSON documentation. All other typings work well.

**Comment by v3ss0n** [comment]
Currently carbon Ui-Shell is totally broken , this PR will hopefully fix it. Please make carbon design usable.

**Comment by theetrain** [comment]
Superseded by #1881

**Pull request closed without merging**
